### ISSUE TITLE
certains formulaires créés dans iCure s'affichent vides dans Topaz

### ISSUE THREAD

**Issue by manuberq** [taktik/icure-backend#17]
Ces schémas s'ouvrent correctement dans iCure; pour le moment:
- schéma kiné
- examen tête et cou
- échelle de Katz: s'affiche mais sans les titres

**Comment by aduchate** [comment]
Les schemas ne sont pas encore supportés... Je vais voir ce qui se passe pour Katz

**Comment by manuberq** [comment]
ok maintenant pour examen tête et cou et un nouveau que je viens de rajouter (examen thorax). Pas ok pour Katz mais moins urgent. Merci Antoine
