### ISSUE TITLE
Questions sur les formulaires

### ISSUE THREAD

**Issue by manuberq** [taktik/icure-backend#19]
1. Le nom que je donne au nouveau service est-il enregistré comme tel dans la base de données ? Question sous-jacente: si je lui donne le même nom que celui de la mesure correspondante dans Medinote (tblMeas), cela facilite-t-il la migration ?
exemples: headEyes pour Yeux, orlSinus pour Points sinusaux, etc
2. La légende que je mets pour le service correspond-elle à la traduction en français ? Pour traduire le formulaire, il suffirait alors de faire la traduction dans Github ? Ou bien je dois refaire le formulaire en NL ?
3. Pour les mesures correspondant à un résultat de labo, exemple cholestérol + date (à encoder manuellement dans un formulaire quand on a reçu le résultat en pdf ou papier, via hub par exemple): comment faire pour qu'un historique reprenne la même mesure arrivée par un import de labo ?
4. Longueur maximale pour un formulaire ?
5. Comme discuté le 11/7, possibilité de récupérer l'ensemble des formulaires existants pour les adapter à Topaz ?

**Comment by aduchate** [comment]
1. Oui. Le nom utilisé lors de la création. Tu peux donner le même nom que dans Medinote, il y a une notion de label qui permet de changer le nom affiché via l'inspecteur.

2. Il faut faire un formulaire en NL

3. Il va falloir faire quelque chose de custom... A diuscuter

4. Pas de vraie limitation. Mais il vaut mieux créer des sous-formulaires assez courts

5. Tu veux dire, ceux de iCure ?
Je vais demander à Adrien de les ajouter dans une autre db
