### ISSUE TITLE
Health element creation: opening date is always today

### ISSUE THREAD

**Issue by cebamps** [taktik/icure-backend#20]
In iCure-web, the start date in the health element creation form is not taken into account: it is always set to today's date.

The cause seems to that the backend always sets a healthElement's openingDate to the current date. See line 85:
https://github.com/taktik/icure-backend/blob/4fa843dc8f1672f0b0400661e611145c010432ec/src/main/java/org/taktik/icure/logic/impl/HealthElementLogicImpl.java#L77-L97

**Comment by gpiroux** [comment]
It seems to be fixed. @cebamps  Could you check ?

**Comment by manuberq** [comment]
ok chez moi

**Comment by cebamps** [comment]
OK with me too!
