### ISSUE TITLE
Ajout traitement médicamenteux: liste de diagnostics au lieu d'une liste de médicaments

### ISSUE THREAD

**Issue by manuberq** [taktik/icure-backend#25]
Colonne de gauche, Traitements médicamenteux, clic sur + -> sélectionner médications: on arrive sur une  liste de diagnostics au lieu d'une liste de médicaments.

**Comment by maxime2018** [comment]
Effectivement, il y a un problème, mais cette fenêtre va être totalement revue dans les prochains jours

**Comment by manuberq** [comment]
ok ce jour, on arrive sur liste de médicaments (sans pouvoir y mettre de posologie mais je clôture ce bug-ci)
